name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Test Python
      id: test-python
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test Python
        setup-command: sudo -H pip3 install pytest
        command: python -m pytest test.py
        timeout: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST-PYTHON_RESULTS: "${{steps.test-python.outputs.result}}"
      with:
        runners: test-python
